= Commerce Cloud Data Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../../assets/images/
Support Category: Select
Commerce Cloud Data Connector Version Major.Minor.Patch
// Anypoint Connector for Commerce Cloud Data Connector provides ...
== About Commerce Cloud Data Connector

Anypoint Connector for Data API Connector (Commerce Cloud Data Connector) is an operation-based connector, which means that when you add the connector to your flow, you need to configure a specific operation for the connector to perform. 

Commerce Cloud Data Connector enables the user to access the Commerce Cloud Data API by using certain configurations, and to then access the data, update the data, and delete the data, as required.


== Mule Compatibility

[width="100%", options="header"]
|=======
|Application or Service |Version
|Mule runtime engine |4.2.1 and later
|Anypoint Studio | 7 and later
|=======


== Prerequisites

Before creating an app, you must have access to the Commerce Cloud Data Connector target resource and
Anypoint Platform. You also need to understand how to create a Mule app using
Anypoint Design Center (Design Center) or Anypoint Studio (Studio). 

Further, you must be familiar with Mule runtime engine (Mule), Anypoint Connectors, Anypoint Studio Essentials, Mule flows, and Mule Global Elements.

To use Commerce Cloud Data Connector, you need:

* Anypoint Studio version 7 and later
* Commerce Cloud Data Connector
* Commerce cloud credentials to access Data API


== Audience
* Starting user
To create your Mule app,
see xref:data-api-connector-design-center.adoc[Design Center Configuration]
or xref:data-api-connector-studio.adoc[Studio Configuration].The
xref:data-api-connector-examples.adoc[Examples] topic provides one or more use
cases for using the connector.
* Power user
Read the xref:data-api-connector-xml-maven.adoc[XML and Maven
Support] and xref:data-api-connector-examples.adoc[Examples] topics.

== Common Use Cases For the Connector
See xref:data-api-connector-examples.adoc[Examples] for a simple use case.


== Next Step

After you meet the prerequisites and experiment with templates and
examples, you are ready to create an app with
xref:data-api-connector-design-center.adoc[Design Center] or
xref:data-api-connector-studio.adoc[Anypoint Studio].

== See Also

* https://www.mulesoft.com/exchange/?search=commerce-cloud-data-connector&type=connector[Anypoint
Exchange]
* https://forums.mulesoft.com[MuleSoft Forum]